### PR TITLE
add old hash for compatibility

### PR DESCRIPTION
**Pull request by lostincode**
https://github.com/CodeSleeve/stapler/pull/116 was a breaking change. This allows for backwards compatibility. :)

### CODE REVIEW

**Comment by milesj** [comment]
It should probably be the reverse. My changes should be `:secure_hash` or something, while the old functionality remains in tact. This will allow BC.

**Comment by lostincode** [comment]
@milesj I'm cool with that - done.

**Comment by tabennett** [comment]
I'm gonna merge this into master real quick and play around with it a bit.  If everything checks out I'll tag a hot fix release later day.

**Comment by milesj** [comment]
Nice, looks good! Thanks for the quick fix @lostincode

**Comment by lostincode** [comment]
@tabennett Thanks. Any luck with a tag?

**Pull request merged**
