### PR TITLE
urlencode path values for url()

### PR DESCRIPTION
**Pull request by benallfree**
Fixes https://github.com/CodeSleeve/stapler/issues/146

### CODE REVIEW

**Comment by kyranb** [comment]
Thanks! :bow:

**Comment by tabennett** [comment]
While this may be a quick fix for the problem, it's really not something that I want merged into the codebase. Adding more and more parameter passing into these methods of these classes isn't really a scalable solution; There's no possible way to cover all scenarios that people are going to come up with. I would much rather prefer the use of inheritance (for the interpolator) to fix this issue. 

We already have the ability to bind implementations for an interpolator (so that users can substitute their own interpolator implementations). Taking that a step further, because we only need perform that check and url encoding if we're interpolation a url, why can't we have two interpolators (1 for paths, 1 for urls) that both extend the base interpolator (for shared functionality) but have different implementations (the url interpolator will encode values).

**Comment by benallfree** [comment]
Good idea, I'll look at a refactor!

**Comment by benallfree** [comment]
I think this is fixed by #167 and isn't needed anymore.

**Comment by benallfree** [comment]
Closing, I think it's not needed.

**Pull request closed without merging**
