### PR TITLE
Extended regex to check for mime types

### PR DESCRIPTION
**Pull request by mvdstam**

### CODE REVIEW

**Comment by czim** [comment]
Any chances of getting this merged soon? This fixes a pretty annoying bug where totally valid data URIs get mishandled...

**Comment by mvdstam** [comment]
Ping @tabennett :smile:

**Comment by tabennett** [comment]
@mvdstam Can you give me some details on what this is doing and why (use case, etc)?

**Comment by czim** [comment]
Right now it only matches some mime-types, but not all that are valid. The regex is too strict.

A data URI with a mime-type of `image/jpeg` will work fine, but data URIs with `application/x-mplayer2` or `image/vnd.rn-realflash` will not be matched by the regex (because it won't allow for '-', '+', etc), so it will fail to detect and treat those as data URIs.

**Comment by mvdstam** [comment]
Awesome, thank you.

**Pull request merged**
